### ISSUE TITLE
The implementation idea of the algorithm for computing curvature

### ISSUE THREAD

**Issue by yun-lai-yun-qu** [SPOCKnots/pyknotid#10]
Hello, author, @dotmet @inclement @xcapaldi ,I would like to ask what is the implementation logic of the algorithm for calculating curvature, torsion and tortuosity? Where can I find it? I don't see it in the text, thank you

**Comment by xcapaldi** [comment]
I'm sorry, I only contributed a small patch to this project and was not involved during the original implementation. I think you'll need to just note the logic from the code itself.

**Comment by inclement** [comment]
The logic for these calculations is in pyknotid/spacecurve.py, e.g. https://github.com/SPOCKnots/pyknotid/blob/master/pyknotid/spacecurves/spacecurve.py#L1095 for the curvature.
